---
name: Github pr approved status

on: # yamllint disable-line rule:truthy
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'PR approved'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
